### ISSUE TITLE
Save row option

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-cloud#1]
Maybe we add an extra tab here - that says 'save row to Pootle Cloud'

It feels like it should be at this level

And there users can

1) Login (if not logged in)
2) Save row
3) Manage templates
4) Log out of PootleCloud

![screen shot 2017-06-30 at 17 10 57](https://user-images.githubusercontent.com/3070779/27744368-2ba13a64-5db7-11e7-9484-256b7432f048.png)

**Comment by shramee** [comment]
Continued from https://github.com/pootlepress/pootle-page-builder/issues/612

**Comment by jamiemarsland** [comment]
Let's change the label to say "Save row to PootleCloud'
