### ISSUE TITLE
Shall we fix the modal so it doesn't scroll?

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-cloud#21]
See video - maybe nicer if the modal doesn't scroll down the page

https://www.dropbox.com/s/mmlsa4spkjk9y4p/pootle%20cloud%20fixed%20modal.mp4?dl=0

**Comment by shramee** [comment]
Hi,

I have been thinking about this since quite some time... making all dialogs fixed so they don't move on scrolling ;)
