### ISSUE TITLE
Different amount of my templates showing in 'drag and drop module' and 'PootleCloud

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-cloud#4]
Pootle Cloud is only showing 7 available, whereas in the drag and drop 'my templates' I see 20

![screen shot 2017-07-04 at 16 49 06](https://user-images.githubusercontent.com/3070779/27836809-f3bf41de-60d8-11e7-9e47-9573f4780136.png)
![screen shot 2017-07-04 at 16 48 57](https://user-images.githubusercontent.com/3070779/27836811-f509b222-60d8-11e7-8ce4-5fd66fa4acaf.png)

**Comment by shramee** [comment]
Aah... latest app not released. 😅
